package ng.com.sirteefyapps.sirteefymovies.services.navigation

import ng.com.sirteefyapps.sirteefymovies.models.Movie
import ng.com.sirteefyapps.sirteefymovies.models.Response
import ng.com.sirteefyapps.sirteefymovies.models.Type

fun getMovies(): List<Movie> {
    return listOf<Movie>(
        Movie(
            title = "The Matrix",
            year = "1999",
            rated = "R",
            released = "31 Mar 1999",
            runtime = "136 min",
            genre = "Action, Sci-Fi",
            director = "Lana Wachowski, Lilly Wachowski",
            writer = "Lana Wachowski, Lilly Wachowski",
            actors = "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
            plot = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
            language = "English",
            country = "United States, Australia",
            awards = "Won 4 Oscars. Another 34 wins & 48 nominations.",
            poster = "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyOTYyMzUxNl5BMl5BanBnXkFtZTcwNTg0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
            metaScore = "73",
            imdbRating = "8.7",
            imdbVotes = "1,722,000",
            imdbID = "tt0133093",
            type = Type.Movie,
            response = Response.True,
            images = listOf(
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg"
            )
        ),
        Movie(
            title = "The Matrix Reloaded",
            year = "2003",
            rated = "R",
            released = "15 May 2003",
            runtime = "138 min",
            genre = "Action, Sci-Fi",
            director = "Lana Wachowski, Lilly Wachowski",
            writer = "Lana Wachowski, Lilly Wachowski",
            actors = "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
            plot = "Neo and his team must return to the Matrix in order to prevent a global catastrophe.",
            language = "English, French",
            country = "United States, Australia",
            awards = "5 wins & 38 nominations.",
            poster = "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
            metaScore = "62",
            imdbRating = "7.2",
            imdbVotes = "518,000",
            imdbID = "tt0234215",
            type = Type.Movie,
            response = Response.True,
            images = listOf(
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
            ),

            ),
        Movie(
            title = "The Matrix",
            year = "1999",
            rated = "R",
            released = "31 Mar 1999",
            runtime = "136 min",
            genre = "Action, Sci-Fi",
            director = "Lana Wachowski, Lilly Wachowski",
            writer = "Lana Wachowski, Lilly Wachowski",
            actors = "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
            plot = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
            language = "English",
            country = "United States, Australia",
            awards = "Won 4 Oscars. Another 34 wins & 48 nominations.",
            poster = "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
            metaScore = "73",
            imdbRating = "8.7",
            imdbVotes = "1,722,000",
            imdbID = "tt0133093",
            type = Type.Movie,
            response = Response.True,
            images = listOf(
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg"
            )
        ),
        Movie(
            title = "The Matrix",
            year = "1999",
            rated = "R",
            released = "31 Mar 1999",
            runtime = "136 min",
            genre = "Action, Sci-Fi",
            director = "Lana Wachowski, Lilly Wachowski",
            writer = "Lana Wachowski, Lilly Wachowski",
            actors = "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
            plot = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
            language = "English",
            country = "United States, Australia",
            awards = "Won 4 Oscars. Another 34 wins & 48 nominations.",
            poster = "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
            metaScore = "73",
            imdbRating = "8.7",
            imdbVotes = "1,722,000",
            imdbID = "tt0133093",
            type = Type.Movie,
            response = Response.True,
            images = listOf(
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg"
            )
        ),
        Movie(
            title = "The Matrix",
            year = "1999",
            rated = "R",
            released = "31 Mar 1999",
            runtime = "136 min",
            genre = "Action, Sci-Fi",
            director = "Lana Wachowski, Lilly Wachowski",
            writer = "Lana Wachowski, Lilly Wachowski",
            actors = "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
            plot = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
            language = "English",
            country = "United States, Australia",
            awards = "Won 4 Oscars. Another 34 wins & 48 nominations.",
            poster = "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
            metaScore = "73",
            imdbRating = "8.7",
            imdbVotes = "1,722,000",
            imdbID = "tt0133093",
            type = Type.Movie,
            response = Response.True,
            images = listOf(
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg"
            )
        ),
        Movie(
            title = "The Matrix",
            year = "1999",
            rated = "R",
            released = "31 Mar 1999",
            runtime = "136 min",
            genre = "Action, Sci-Fi",
            director = "Lana Wachowski, Lilly Wachowski",
            writer = "Lana Wachowski, Lilly Wachowski",
            actors = "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
            plot = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
            language = "English",
            country = "United States, Australia",
            awards = "Won 4 Oscars. Another 34 wins & 48 nominations.",
            poster = "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
            metaScore = "73",
            imdbRating = "8.7",
            imdbVotes = "1,722,000",
            imdbID = "tt0133093",
            type = Type.Movie,
            response = Response.True,
            images = listOf(
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg",
                "https://m.media-amazon.com/images/I/71c71fJ6FfL._AC_SY679_.jpg"
            )
        ),

        )
}